/**
 * 表单字段配置   分组、显示单位和 3D 高亮区域映射
 */
const rawFieldGroups = [
  {
    id: 'gate',
    title: '闸室',
    fields: [
      {
        key: '闸室长',
        label: '闸室长',
        unit: 'cm',
        part: 'gate',
        region: 'floor',
      },
      {
        key: '闸孔净宽',
        label: '闸孔净宽',
        unit: 'cm',
        part: 'gate',
        region: 'opening',
      },
      {
        key: '闸底板厚',
        label: '闸底板厚',
        unit: 'cm',
        part: 'gate',
        region: 'floor',
      },
      {
        key: '边墩厚',
        label: '边墩厚',
        unit: 'cm',
        part: 'gate',
        region: 'pier',
      },
      {
        key: '中墙厚',
        label: '中墙厚',
        unit: 'cm',
        part: 'gate',
        region: 'middlePier',
      },
      {
        key: '闸墩高',
        label: '闸墩高',
        unit: 'cm',
        part: 'gate',
        region: 'pier',
      },
      {
        key: '齿墙高',
        label: '齿墙高',
        unit: 'cm',
        part: 'gate',
        region: 'tooth',
      },
      {
        key: '齿墙宽',
        label: '齿墙宽',
        unit: 'cm',
        part: 'gate',
        region: 'tooth',
      },
      {
        key: '闸门距上游',
        label: '闸门距上游',
        unit: 'cm',
        part: 'gate',
        region: 'door',
      },
      {
        key: '闸门厚',
        label: '闸门厚',
        unit: 'cm',
        part: 'gate',
        region: 'door',
      },
      {
        key: '门槽入闸墩深',
        label: '门槽入闸墩深',
        unit: 'cm',
        part: 'gate',
        region: 'slot',
      },
      {
        key: '门槽深',
        label: '门槽深',
        unit: 'cm',
        part: 'gate',
        region: 'slot',
      },
      {
        key: '门槽二期宽',
        label: '门槽二期宽',
        unit: 'cm',
        part: 'gate',
        region: 'slot',
      },
      {
        key: '检修桥入闸墩深',
        label: '检修桥入闸墩深',
        unit: 'cm',
        part: 'gate',
        region: 'serviceBridge',
      },
      {
        key: '检修桥板厚',
        label: '检修桥板厚',
        unit: 'cm',
        part: 'gate',
        region: 'serviceBridge',
      },
      {
        key: '检修桥板宽',
        label: '检修桥板宽',
        unit: 'cm',
        part: 'gate',
        region: 'serviceBridge',
      },
      {
        key: '交通桥宽',
        label: '交通桥宽',
        unit: 'cm',
        part: 'gate',
        region: 'trafficBridge',
      },
      {
        key: '交通桥厚',
        label: '交通桥厚',
        unit: 'cm',
        part: 'gate',
        region: 'trafficBridge',
      },
      {
        key: '桥边距上游',
        label: '桥边距上游',
        unit: 'cm',
        part: 'gate',
        region: 'trafficBridge',
      },
      {
        key: '搭板长',
        label: '搭板长',
        unit: 'cm',
        part: 'gate',
        region: 'approachSlab',
      },
      {
        key: '交通桥护边厚',
        label: '交通桥护边厚',
        unit: 'cm',
        part: 'gate',
        region: 'trafficBridge',
      },
      {
        key: '交通桥护边高',
        label: '交通桥护边高',
        unit: 'cm',
        part: 'gate',
        region: 'trafficBridge',
      },
    ],
  },
  {
    id: 'stilling',
    title: '消力池',
    fields: [
      {
        key: '消力池陡坡段平直段长度',
        label: '陡坡段平直段长度',
        unit: 'cm',
        part: 'stilling',
        region: 'slope',
      },
      {
        key: '消力池陡坡段长度',
        label: '陡坡段长度',
        unit: 'cm',
        part: 'stilling',
        region: 'slope',
      },
      {
        key: '消力池陡坡段高差',
        label: '陡坡段高差',
        unit: 'cm',
        part: 'stilling',
        region: 'slope',
      },
      {
        key: '消力池长度',
        label: '消力池长度',
        unit: 'cm',
        part: 'stilling',
        region: 'pool',
      },
      {
        key: '消力池底板厚度',
        label: '底板厚度',
        unit: 'cm',
        part: 'stilling',
        region: 'floor',
      },
      {
        key: '消力池齿墙底宽',
        label: '齿墙底宽',
        unit: 'cm',
        part: 'stilling',
        region: 'tooth',
      },
      {
        key: '消力池齿墙高度',
        label: '齿墙高度',
        unit: 'cm',
        part: 'stilling',
        region: 'tooth',
      },
      {
        key: '消力池陡坡段上部墙宽',
        label: '陡坡段上部墙宽',
        unit: 'cm',
        part: 'stilling',
        region: 'wall',
      },
      {
        key: '消力池陡坡段下部墙宽',
        label: '陡坡段下部墙宽',
        unit: 'cm',
        part: 'stilling',
        region: 'wall',
      },
      {
        key: '消力池墙高',
        label: '消力池墙高',
        unit: 'cm',
        part: 'stilling',
        region: 'wall',
      },
      {
        key: '消力池斜墙段高度',
        label: '斜墙段高度',
        unit: 'cm',
        part: 'stilling',
        region: 'wall',
      },
      {
        key: '消力坎高',
        label: '消力坎高',
        unit: 'cm',
        part: 'stilling',
        region: 'baffle',
      },
      {
        key: '消力坎顶宽',
        label: '消力坎顶宽',
        unit: 'cm',
        part: 'stilling',
        region: 'baffle',
      },
    ],
  },
  {
    id: 'upstreamConnection',
    title: '上游连接',
    fields: [
      {
        key: '上游连接段底板长度',
        label: '底板长度',
        unit: 'cm',
        part: 'upstreamConnection',
        region: 'floor',
      },
      {
        key: '上游连接段底板厚度',
        label: '底板厚度',
        unit: 'cm',
        part: 'upstreamConnection',
        region: 'floor',
      },
      {
        key: '上游连接段底板齿墙高',
        label: '底板齿墙高',
        unit: 'cm',
        part: 'upstreamConnection',
        region: 'tooth',
      },
      {
        key: '上游连接段底板齿墙宽',
        label: '底板齿墙宽',
        unit: 'cm',
        part: 'upstreamConnection',
        region: 'tooth',
      },
      {
        key: '上游连接段坡顶压坡宽',
        label: '坡顶压坡宽',
        unit: 'cm',
        part: 'upstreamConnection',
        region: 'slope',
      },
      {
        key: '上游连接段坡底槽宽',
        label: '坡底槽宽',
        unit: 'cm',
        part: 'upstreamConnection',
        region: 'ditch',
      },
      {
        key: '上游连接段坡底槽高',
        label: '坡底槽高',
        unit: 'cm',
        part: 'upstreamConnection',
        region: 'ditch',
      },
      {
        key: '上游连接段坡底外槽宽',
        label: '坡底外槽宽',
        unit: 'cm',
        part: 'upstreamConnection',
        region: 'ditch',
      },
      {
        key: '上游连接段坡板厚度',
        label: '坡板厚度',
        unit: 'cm',
        part: 'upstreamConnection',
        region: 'slope',
      },
      {
        key: '上游连接段坡齿厚度',
        label: '坡齿厚度',
        unit: 'cm',
        part: 'upstreamConnection',
        region: 'slope',
      },
      {
        key: '上游连接段坡齿宽度',
        label: '坡齿宽度',
        unit: 'cm',
        part: 'upstreamConnection',
        region: 'slope',
      },
    ],
  },
  {
    id: 'upstreamTransition',
    title: '上游渐变',
    fields: [
      {
        key: '上游渐变段中首断面距离',
        label: '中首断面距离',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'length',
      },
      {
        key: '上游渐变段中断面底宽',
        label: '中断面底宽',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'middle',
      },
      {
        key: '上游渐变段中断面坡高',
        label: '中断面坡高',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'middle',
      },
      {
        key: '上游渐变段中断面坡宽',
        label: '中断面坡宽',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'middle',
      },
      {
        key: '上游渐变段中断面趾高',
        label: '中断面趾高',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'toe',
      },
      {
        key: '上游渐变段中断面趾宽',
        label: '中断面趾宽',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'toe',
      },
      {
        key: '上游渐变段中断面踵高',
        label: '中断面踵高',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'heel',
      },
      {
        key: '上游渐变段中断面顶端高',
        label: '中断面顶端高',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'wallTop',
      },
      {
        key: '上游渐变段中断面顶端宽',
        label: '中断面顶端宽',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'wallTop',
      },
      {
        key: '上游渐变段上断面铺盖宽',
        label: '上断面铺盖宽',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'upper',
      },
      {
        key: '上游渐变段上断面坡高',
        label: '上断面坡高',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'upper',
      },
      {
        key: '上游渐变段上断面坡宽',
        label: '上断面坡宽',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'upper',
      },
      {
        key: '上游渐变段上断面底宽',
        label: '上断面底宽',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'upper',
      },
      {
        key: '上游渐变段下断面底宽',
        label: '下断面底宽',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'lower',
      },
      {
        key: '上游渐变段下断面坡高',
        label: '下断面坡高',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'lower',
      },
      {
        key: '上游渐变段断面铺盖厚',
        label: '断面铺盖厚',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'floor',
      },
      {
        key: '上游渐变段铺盖齿墙高',
        label: '铺盖齿墙高',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'tooth',
      },
      {
        key: '上游渐变段铺盖齿墙宽',
        label: '铺盖齿墙宽',
        unit: 'cm',
        part: 'upstreamTransition',
        region: 'tooth',
      },
    ],
  },
  {
    id: 'downstreamConnection',
    title: '下游连接',
    fields: [
      {
        key: '下游连接段底板长度',
        label: '底板长度',
        unit: 'cm',
        part: 'downstreamConnection',
        region: 'floor',
      },
      {
        key: '下游连接段底板厚度',
        label: '底板厚度',
        unit: 'cm',
        part: 'downstreamConnection',
        region: 'floor',
      },
      {
        key: '下游连接段底板齿墙高',
        label: '底板齿墙高',
        unit: 'cm',
        part: 'downstreamConnection',
        region: 'tooth',
      },
      {
        key: '下游连接段底板齿墙宽',
        label: '底板齿墙宽',
        unit: 'cm',
        part: 'downstreamConnection',
        region: 'tooth',
      },
      {
        key: '下游连接段坡顶压坡宽',
        label: '坡顶压坡宽',
        unit: 'cm',
        part: 'downstreamConnection',
        region: 'slope',
      },
      {
        key: '下游连接段坡底槽宽',
        label: '坡底槽宽',
        unit: 'cm',
        part: 'downstreamConnection',
        region: 'ditch',
      },
      {
        key: '下游连接段坡底槽高',
        label: '坡底槽高',
        unit: 'cm',
        part: 'downstreamConnection',
        region: 'ditch',
      },
      {
        key: '下游连接段坡底外槽宽',
        label: '坡底外槽宽',
        unit: 'cm',
        part: 'downstreamConnection',
        region: 'ditch',
      },
      {
        key: '下游连接段坡板厚度',
        label: '坡板厚度',
        unit: 'cm',
        part: 'downstreamConnection',
        region: 'slope',
      },
      {
        key: '下游连接段坡齿厚度',
        label: '坡齿厚度',
        unit: 'cm',
        part: 'downstreamConnection',
        region: 'slope',
      },
      {
        key: '下游连接段坡齿宽度',
        label: '坡齿宽度',
        unit: 'cm',
        part: 'downstreamConnection',
        region: 'slope',
      },
    ],
  },
  {
    id: 'downstreamTransition',
    title: '下游渐变',
    fields: [
      {
        key: '下游渐变段中末断面距离',
        label: '中末断面距离',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'length',
      },
      {
        key: '下游渐变段中断面底宽',
        label: '中断面底宽',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'middle',
      },
      {
        key: '下游渐变段中断面坡宽',
        label: '中断面坡宽',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'middle',
      },
      {
        key: '下游渐变段中断面趾高',
        label: '中断面趾高',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'toe',
      },
      {
        key: '下游渐变段中断面趾宽',
        label: '中断面趾宽',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'toe',
      },
      {
        key: '下游渐变段中断面踵高',
        label: '中断面踵高',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'heel',
      },
      {
        key: '下游渐变段中断面顶端高',
        label: '中断面顶端高',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'wallTop',
      },
      {
        key: '下游渐变段中断面顶端宽',
        label: '中断面顶端宽',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'wallTop',
      },
      {
        key: '下游渐变段上断面底宽',
        label: '上断面底宽',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'upper',
      },
      {
        key: '下游渐变段下断面铺盖宽',
        label: '下断面铺盖宽',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'lower',
      },
      {
        key: '下游渐变段下断面底宽',
        label: '下断面底宽',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'lower',
      },
      {
        key: '下游渐变段下断面坡宽',
        label: '下断面坡宽',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'lower',
      },
      {
        key: '下游渐变段断面铺盖厚',
        label: '断面铺盖厚',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'floor',
      },
      {
        key: '下游渐变段铺盖齿墙高',
        label: '铺盖齿墙高',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'tooth',
      },
      {
        key: '下游渐变段铺盖齿墙宽',
        label: '铺盖齿墙宽',
        unit: 'cm',
        part: 'downstreamTransition',
        region: 'tooth',
      },
    ],
  },
]
/**
 * 为厘米字段补充尺寸线标识
 * guideRegion 使用部件和参数键组成稳定区域
 * 避免多个字段共用同一个实体区域时尺寸线互相串联
 */
export const fieldGroups = rawFieldGroups.map((group) => ({
  ...group,
  fields: group.fields.map((field) => ({
    ...field,
    guideRegion: field.unit === 'cm' ? `${field.part}.${field.key}` : undefined,
  })),
}))
